### ISSUE TITLE
对数据库执行 SQL 后应用崩溃

### ISSUE THREAD

**Issue by machinefixer** [rob2468/HttpServerDebug#2]
真机不连接 Xcode 独立运行应用，进入 `HSDHttpServerControlPannelController` 启动 HSD 服务器，然后在 Mac 上的 Web 页面访问 HSD 控制台的数据库页面，能够正确浏览指定 SQLite 数据库的数据，但是执行 SQL 的时候崩溃。

iOS 版本： 10.1

截图：
<img width="454" alt="2018-05-21 12 57 41" src="https://user-images.githubusercontent.com/5358642/40291445-ad9c83b2-5cf7-11e8-874f-46253a27dc17.png">

**Comment by rob2468** [comment]
我在Sample工程复现不出来。
方便连接Xcode跑一次，截个崩溃堆栈的图吗？看下崩在哪个地方

**Comment by machinefixer** [comment]
@rob2468 嗯，我连接 Xcode 后执行 SQL 崩溃的调用栈是这样的：
<img width="1440" alt="2018-05-21 14 17 44" src="https://user-images.githubusercontent.com/5358642/40293242-96aa543a-5d02-11e8-92dc-e7806a905e16.png">
<img width="471" alt="2018-05-21 14 18 08" src="https://user-images.githubusercontent.com/5358642/40293247-988a0ec6-5d02-11e8-8c1c-31f838601977.png">

从崩溃的那一行看来是 set 了一个 nil 给一个 key, 这个 key 我看了一下是我的 message 表中的一个字段名。

**Comment by machinefixer** [comment]
@rob2468 补充一个信息，我的 message 表的 jsonContent 是以 blob 类型存储的。

<img width="92" alt="2018-05-21 14 45 12" src="https://user-images.githubusercontent.com/5358642/40293927-c375118c-5d05-11e8-8c1d-c632bb238022.png">
<img width="112" alt="2018-05-21 14 45 00" src="https://user-images.githubusercontent.com/5358642/40293931-c58a7570-5d05-11e8-9ea1-ed2f9a57fab5.png">

**Comment by rob2468** [comment]
定位原因了，是 `-[FMDatabase executeStatements:withResultBlock:]` 接口没处理好 blob 类型的数据。
我处理一下。

**Comment by machinefixer** [comment]
好的，谢谢

**Comment by rob2468** [comment]
https://github.com/rob2468/HttpServerDebug/commit/b19fbf77c2f83d440bb1066e55cc81055650330c
已修复
