### ISSUE TITLE
file explorer 右键上传没反应

### ISSUE THREAD

**Issue by k1er** [rob2468/HttpServerDebug#4]
Chrome 和 Safari中使用file explorer功能，下载、删除、查看都可能正常使用，右键上传没有反应，跟使用姿势有关系吗

**Comment by k1er** [comment]
运行demo是可以上传的，集成到项目中不work，有什么相关设置吗，我是通过pod集成的

**Comment by k1er** [comment]
发现是pod版本比较老导致的，更改本地podSec文件到最新的commit即可解决

**Comment by rob2468** [comment]
多谢指明问题 这周更新下 pod 源
